INSERT INTO tb_category(name)VALUES ('MATERIAL LIMPEZA')
INSERT INTO tb_category(name)VALUES ('BEBIDAS')
INSERT INTO tb_category(name)VALUES ('BOMBONIER')
INSERT INTO tb_category(name)VALUES ('SALGADINHOS')
INSERT INTO tb_category(name)VALUES ('CHÁS')
INSERT INTO tb_category(name)VALUES ('CAFÉ')
INSERT INTO tb_category(name)VALUES ('GRÃOS')
INSERT INTO tb_category(name)VALUES ('CERREAIS')
INSERT INTO tb_category(name)VALUES ('VERDURAS')
INSERT INTO tb_category(name)VALUES ('FRUTAS')
INSERT INTO tb_category(name)VALUES ('CARNES')
INSERT INTO tb_category(name)VALUES ('LACTINIOS')