INSERT INTO tb_category(name)VALUES ('MATERIAL LIMPEZA')
INSERT INTO tb_category(name)VALUES ('BEBIDAS')
INSERT INTO tb_category(name)VALUES ('BOMBONIER')
INSERT INTO tb_category(name)VALUES ('SALGADINHOS')
INSERT INTO tb_category(name)VALUES ('CHÁS')
INSERT INTO tb_category(name)VALUES ('CAFÉ')
INSERT INTO tb_category(name)VALUES ('GRÃOS')
INSERT INTO tb_category(name)VALUES ('CEREAIS')
INSERT INTO tb_category(name)VALUES ('VERDURAS')
INSERT INTO tb_category(name)VALUES ('FRUTAS')
INSERT INTO tb_category(name)VALUES ('CARNES')
INSERT INTO tb_category(name)VALUES ('LACTINIOS')
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('DETEREGENTE', 12.2, 'UNIDADE', 1)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('SABÃO EM PÓ', 4.50, 'UNIDADE', 1)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('SABÃO EM BARRA', 7.53, 'UNIDADE', 1)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('CLORO', 9.0, 'UNIDADE', 1)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('AMACIANTE', 22.50, 'UNIDADE', 1)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('ESPONJA', 2.30, 'UNIDADE', 1)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('BOMBRIL', 3.59, 'UNIDADE', 1)

INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('ARROZ MARINHA', 22.80, 'KILOGRAMA', 8)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('FEIJÃO', 12.0, 'KILOGRAMA', 8)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('AÇUCAR', 8.20, 'KILOGRAMA', 8)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('FARINHA', 15.10, 'KILOGRAMA', 8)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('ARROZ EXERCITO', 25.80, 'KILOGRAMA', 8)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('FEIJÃO BRASILIA', 9.90, 'KILOGRAMA', 8)
INSERT INTO tb_product(name, price, unit_measure, category_id)VALUES ('ARROZ AERONÁUTICA', 35.10, 'KILOGRAMA', 8)