name: CD
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache de deps
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: RUN MVN CLEAN
        run: mvn clean

      - name: RUN MVN PACKAGE
        run: mvn package

      - name: LOGIN CONTAINER REGISTER
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login

      - name: PUSH CONTAINER REGISTER
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:push -a ${{secrets.HEROKU_APP_NAME}} web

      - name: RELEASE CONTAINER REGISTER
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:release -a ${{secrets.HEROKU_APP_NAME}} web