name: CI
on:
  push:
    branches:
      - '*'
jobs:
  in-docker_test:
    name: Testes automatizados
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        -
      - name: Set JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Cache das Dependencias
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Executar Teste
        run: mvn -B test